# import packages

In [1]:
import json
import pandas as pd

# read the json file (raw tweet data)

In [26]:
filename = 'first_collection.txt'
cur_file = open(filename,'r')

# define variables

In [27]:
tweet_count = 0 # counter to keep track no of tweets processed
user_count = 0 # counter to keep track no of unique_user processed

unique_user_id_set = set([])      
all_tweet_information = []
all_user_information = []

# iterate through the file

In [28]:
try:     
    for line in cur_file:
    # if line length is less than 100, that indicates error.
        if (len(line)>100): 
            tweet_object=json.loads(line) # convert "string-line" into json
            # check if json object has a key id. Otherwise continue to next.
            if 'id' in tweet_object.keys(): 
                tweet_count += 1
                # tweet object information
                tweet_id        = tweet_object['id']
                user_id         = tweet_object['user']['id']
                tweet_lang      = tweet_object['lang']
                tweet_time      = str(pd.to_datetime(tweet_object['created_at']))
                source          = tweet_object['source']
                tweet_text      = tweet_object['text']

                # tweet numeric information
                quote_count = tweet_object['quote_count']
                reply_count = tweet_object['reply_count']
                retweet_count = tweet_object['retweet_count']
                tweet_favorite_count = tweet_object['favorite_count']

                # meta-content information
                hashtags = [hashtag['text'] for hashtag in tweet_object['entities']['hashtags']]
                short_urls = [url['url'] for url in tweet_object['entities']['urls']]
                expanded_urls = []
                try:
                    expanded_urls = [url['expanded_url'] for url in tweet_object['entities']['urls']]
                except:
                    print('Error Message: No Expanded URL.')
                expanded_urls = []

                # user interaction based informations    
                user_mentions = [user_mentions['id']\
                            for user_mentions in tweet_object['entities']['user_mentions']]


                tweet_info = [tweet_id, user_id, tweet_lang,\
                        tweet_time, source, tweet_text,\
                        quote_count, reply_count, retweet_count,\
                        tweet_favorite_count, hashtags, short_urls,\
                        expanded_urls, user_mentions]

                all_tweet_information.append(tweet_info)
                # user profile information

                if user_id in unique_user_id_set:
                    pass
                else:
                    unique_user_id_set.add(user_id)
                    user_count += 1
                    user_screen_name      = tweet_object['user']['screen_name']
                    user_name             = tweet_object['user']['name']
                    user_language         = tweet_object['user']['lang']  
                    location              = tweet_object['user']['location']
                    profile_url           = tweet_object['user']['url']
                    description           = tweet_object['user']['description']
                    protected             = tweet_object['user']['protected']
                    verified              = tweet_object['user']['verified']
                    created_at            = str(pd.to_datetime(tweet_object['user']['created_at']))
                    friends_count         = tweet_object['user']['friends_count']
                    followers_count       = tweet_object['user']['followers_count']
                    favorites_count       = tweet_object['user']['favourites_count']
                    statuses_count        = tweet_object['user']['statuses_count']

                    user_information = [user_id, user_screen_name, user_name,\
                           user_language, location, profile_url,\
                           description, protected, verified, created_at,\
                           friends_count, followers_count,\
                           favorites_count, statuses_count]

                    all_user_information.append(user_information)

except Exception as e:
    print(f'Error in reading line. Message: {e}')

# print statistics

In [29]:
print(f"Total Tweet Processed: {tweet_count}")
print(f"Total unique users: {user_count}")

Total Tweet Processed: 70
Total unique users: 70

# define the user_columns

In [30]:
tweet_info_columns = ['tweet_id', 'user_id', 'tweet_lang',\
                      'tweet_time', 'source', 'tweet_text',\
                      'quote_count', 'reply_count', 'retweet_count',\
                      'tweet_favorite_count', 'hashtags', 'short_urls',\
                      'expanded_urls', 'user_mentions']
    
user_info_columns = ['user_id', 'user_screen_name', 'user_name',\
                     'user_language', 'location', 'profile_url',\
                     'description', 'protected', 'verified', 'created_at',\
                     'friends_count', 'followers_count',\
                     'favorites_count', 'statuses_count']

# create the pandas dataframe

In [31]:
tweet_info_dataframe = pd.DataFrame(all_tweet_information, columns=tweet_info_columns)
user_info_dataframe = pd.DataFrame(all_user_information, columns=user_info_columns)

# show the dataframe

In [32]:
tweet_info_dataframe.head()

,tweet_id,user_id,tweet_lang,tweet_time,source,tweet_text,quote_count,reply_count,retweet_count,tweet_favorite_count,hashtags,short_urls,expanded_urls,user_mentions
0,1432734422873382926,829126371704262656,en,2021-08-31 15:57:59+00:00,"<a href=""http://twitter.com/download/android"" ...",RT @DWUhlfelderLaw: Florida changed its COVID-...,0,0,0,0,[],[https://t.co/iU5NGDRNOn],[],[1011970623470489601]
1,1432734423288590338,224664814,en,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @LifeSouth: LifeSouth has reinstated testin...,0,0,0,0,[],[],[],[39806053]
2,1432734424005763074,1385354567739744258,es,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @barbeandi2019: La única reducción qué se n...,0,0,0,0,[],[],[],[702158098840981505]
3,1432734424051769348,1313288977164562432,es,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",#Mañanera Los accidentes son la causa número u...,0,0,0,0,[Mañanera],[https://t.co/ier4gfj6EE],[],[1154180084078501889]
4,1432734425213775875,1283072785326256129,en,2021-08-31 15:58:00+00:00,"<a href=""http://twitter.com/download/android"" ...",RT @oohincensed: It's been over eight months s...,0,0,0,0,[],[],[],[1595327870]

In [33]:
user_info_dataframe.head()

,user_id,user_screen_name,user_name,user_language,location,profile_url,description,protected,verified,created_at,friends_count,followers_count,favorites_count,statuses_count
0,829126371704262656,JustAHuskerGal,Jay ~ Let's Make it Blue in '22 🌊🗳️💙,None,"Nebraska, USA",None,Don't be a lady...Be a legend!\n#FirstNationsT...,False,False,2017-02-08 00:35:06+00:00,4364,3495,316227,162494
1,224664814,MillarLawFirm,The Millar Law Firm - Atlanta Accident Attorneys,None,"Atlanta, GA",https://atlantaadvocate.com/atlanta/,Specializing in Georgia Personal Injury Law | ...,False,False,2010-12-09 15:22:06+00:00,696,734,867,2862
2,1385354567739744258,OlimpiaHku,OᒪIᗰᑭIᗩ ᕼIKᗩᖇᑌ,None,💫 ᖇIᐯEᑎᗪEᒪ💫,None,"LιႦɾҽ, αραʂισɳαԃα, ɾσɱáɳƚιƈα, αʂριɾαƈισɳιʂƚα ყ...",False,False,2021-04-22 22:07:35+00:00,2598,2763,26683,17996
3,1313288977164562432,laroli3,Laura Rojas,None,None,None,Editora de #Espectáculos en @Notimex\nContenid...,False,False,2020-10-06 01:25:09+00:00,30,40,262,6204
4,1283072785326256129,1969Human,Human rights 1969,None,Bathgate Scotland,http://Humanrightsforallsite.wordpress.com,"Disabled Scottish actvist , dpac member , liti...",False,False,2020-07-14 16:16:31+00:00,4999,1046,35431,131495

# save as CSV file

In [34]:
tweet_info_dataframe.to_csv('tweet_info_dataframe.csv')
user_info_dataframe.to_csv('user_info_dataframe.csv')

# read-back the saved CSV files

In [35]:
reloaded_tweet_info_dataframe = pd.read_csv('tweet_info_dataframe.csv')
reloaded_tweet_info_dataframe.head()

,Unnamed: 0,tweet_id,user_id,tweet_lang,tweet_time,source,tweet_text,quote_count,reply_count,retweet_count,tweet_favorite_count,hashtags,short_urls,expanded_urls,user_mentions
0,0,1432734422873382926,829126371704262656,en,2021-08-31 15:57:59+00:00,"<a href=""http://twitter.com/download/android"" ...",RT @DWUhlfelderLaw: Florida changed its COVID-...,0,0,0,0,[],['https://t.co/iU5NGDRNOn'],[],[1011970623470489601]
1,1,1432734423288590338,224664814,en,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @LifeSouth: LifeSouth has reinstated testin...,0,0,0,0,[],[],[],[39806053]
2,2,1432734424005763074,1385354567739744258,es,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @barbeandi2019: La única reducción qué se n...,0,0,0,0,[],[],[],[702158098840981505]
3,3,1432734424051769348,1313288977164562432,es,2021-08-31 15:58:00+00:00,"<a href=""https://mobile.twitter.com"" rel=""nofo...",#Mañanera Los accidentes son la causa número u...,0,0,0,0,['Mañanera'],['https://t.co/ier4gfj6EE'],[],[1154180084078501889]
4,4,1432734425213775875,1283072785326256129,en,2021-08-31 15:58:00+00:00,"<a href=""http://twitter.com/download/android"" ...",RT @oohincensed: It's been over eight months s...,0,0,0,0,[],[],[],[1595327870]